### ISSUE TITLE
[Bug]: Failed to apply Ktorfit plugin

### ISSUE THREAD

**Issue by fobo66** [Foso/Ktorfit#105]
### Ktorfit version

1.0.0-beta17

### What happened and how can we reproduce this issue?

Build fails on CI with the following exception:

```
An exception occurred applying plugin request [id: 'de.jensklingenberg.ktorfit', version: '1.0.0']
> Failed to apply plugin 'de.jensklingenberg.ktorfit'.
   > Cannot add extension with name 'ktorfit', as there is an extension already registered with that name.

```

### What did you expect to happen?

Plugin is correctly applied and build succeeds

### Is there anything else we need to know about?

My [project](https://github.com/fobo66/WearMMR) where you can see the issue in Actions.

**Comment by Foso** [comment]
Hi, the problem is that your dependency is also called ktorfit https://github.com/fobo66/WearMMR/blob/a159258a003de12afe960815900bb60429908867/settings.gradle.kts#L127

**Comment by Foso** [comment]
Hi, i saw that your project is now building. Is the problem solved?

**Comment by fobo66** [comment]
Yeah, I renamed the dependency in version catalog and everything worked. Thanks for your help!

Maybe I should update the README with a note regarding version catalog, or it's unecessary?

**Comment by Foso** [comment]
Thank you for asking, but i don`t think it's necessary
