### ISSUE TITLE
Custom base URL for each function instead of unified base URL

### ISSUE THREAD

**Issue by ahmadmssm** [Foso/Ktorfit#108]
I want to be able to set a custom URL per function, meaning that if I have some APIs with a base URL different from the common one, then I can use it.

Use case: 
Your backend might have a unified URL but the payment gateway or a third-party integration has its own base URL.

**Comment by Foso** [comment]
You can set a base url inside the Http annotations: `@GET("https://example.com/api/test/")`

**Comment by Foso** [comment]
I close this, feel free to reopen it if my suggested solution doesn`t fit your use case
