### ISSUE TITLE
URLs are forced to have / at the end

### ISSUE THREAD

**Issue by ahmadmssm** [Foso/Ktorfit#109]
### Ktorfit version

1.0.0-beta17 

### What happened and how can we reproduce this issue?

When I provide a base URL without `/` at the end, I got a runtime error.

### What did you expect to happen?

This should not be forced as there are some cases where the path is set dynamically and In such case, I had to append `/` at the end of the base URL and remove it programmatically from all the APIs paths.

**Comment by Foso** [comment]
You can turn this off now with https://github.com/Foso/Ktorfit/releases/tag/v1.0.0-beta18

**Comment by ahmadmssm** [comment]
Thanks.
