### ISSUE TITLE
Add support for 'internal' parameter type

### ISSUE THREAD

**Issue by Jovandine** [Foso/Ktorfit#13]
We use 'internal' keyword a lot in our modules. With ktorfit we get errors like this in generated classes:
'public' function exposes its 'internal' parameter type OurInternalRequestParameter

**Comment by Foso** [comment]
Hi, thank you for reporting. I will take a look if i can make this work

**Comment by Foso** [comment]
I looked at it and i don't know how to make it work. The generated create() function needs to have access to the interface/implementation to return it. This doesn't work if it's internal. If someone else has a good idea, i'm happy to hear about it

**Comment by Foso** [comment]
Hi, with 1.0.0-beta17 it now possible to use internal classes/interfaces
