### ISSUE TITLE
Not working with Koin Annotations

### ISSUE THREAD

**Issue by javichaques** [Foso/Ktorfit#14]
**Describe the bug**
Ktorfit doesn't generate code correctly when add [Koin Annotations](https://insert-koin.io/docs/setup/ka_1.0) compiler.

**To Reproduce**
1. Ktorfit is working correctly
2. Then add Koin Annotations Compiler
3. Koin Annotations generate correctly classes but not Ktorfit

**Screenshots**
**Working**

![Captura de Pantalla 2022-06-20 a las 20 05 56](https://user-images.githubusercontent.com/6851391/174657796-4436c2fd-8676-4048-803b-5b31309318c1.png)
![Captura de Pantalla 2022-06-20 a las 20 06 05](https://user-images.githubusercontent.com/6851391/174657798-9c3d1939-6a47-4087-9484-29016ec18997.png)

**Not working**
![Captura de Pantalla 2022-06-20 a las 20 06 48](https://user-images.githubusercontent.com/6851391/174657847-dbf140ec-de2a-461e-be08-6df7d64ed6c2.png)
![Captura de Pantalla 2022-06-20 a las 20 06 59](https://user-images.githubusercontent.com/6851391/174657851-4ae60d0c-1a46-4590-b5c7-72e44d18084d.png)

**Software used**
```
Android Studio Chipmunk | 2021.2.1 Patch 1
Kotlin v1.7.0
KSP 1v.7.0-1.0.6
Ktor v2.0.2
Ktorfit v1.0.0-beta07
Koin v3.2.0
Koin Annotations v1.0.1
```

**Comment by Foso** [comment]
Hi @javichaques , thank you for reporting this. I was able to reproduce that error, unfortunately i'm not sure yet why this happens.

**Comment by javichaques** [comment]
Hi, I have tried the new version and it works correctly, thank @Foso
