### ISSUE TITLE
Use ResponseConverters for suspend functions

### ISSUE THREAD

**Issue by DanielNovak** [Foso/Ktorfit#19]
The documentation doesn't mention it, but `suspend` API functions ignore any defined `ResponseConverters` - is that by design? A look into the source code confirms this, only the non-suspend code in `KtorfitClient.request` uses `getResponseConverters()`.

I am rewriting a Retrofit API and we have our custom response class `Result` which wraps the real response (into `Result.Sucess` and `Result.Failure`) and these API functions are `suspend`. Maybe I could achieve similar functionality with non-suspend functions but it will not be so elegant.

For example we have this:
```
@GET("/someEndpoint")
suspend fun getSomething(): Result<List<SomeEntity>>
```

The `Result` is just our class that is created locally, it's a sealed class with two classes - `Result.Success` and `Result.Failure` and we create them with help of Retrofit's CallDelegates. The same could be achieved with a `ResponseConverter` if it supported `suspend`.

**Comment by DanielNovak** [comment]
I tried to define it without a `suspend` and then create a custom `ResponseConverter` like this:

```
@GET("/someEndpoint")
fun getSomething(): Flow<Result<List<SomeEntity>>>
```

And I seem to be running into issues inside the `ResponseConverter` because `TypeInfo` now also includes the `Result` class and it then tries to parse the response and expects `Result` to be there...

**Comment by DATL4G** [comment]
It's quite easy to get the inner type. I faced the same issue as you.

In my case the interface looks something like this:

```kotlin
interface Example {
    @GET("test")
    fun getTest(): Flow<ApiResponse<String>>>
}
```

To get the inner type I created this function:

```kotlin
fun TypeInfo.innerType(): TypeInfo? {
    val kotlinType = this.kotlinType ?: return null
    val modelKTypeProjection = if (kotlinType.arguments.size >= 0) kotlinType.arguments[0] else return null
    val modelKType = modelKTypeProjection.type ?: return null
    val modelClass = (modelKType.classifier as? KClass<*>?) ?: return null
    return TypeInfo(modelClass, modelKType.platformType, modelKType)
}
```

Anf finally my ResponseConverter looks like this:

```kotlin
class ExampleResponseConverter : ResponseConverter {
    override fun supportedType(returnTypeName: String): Boolean {
        return returnTypeName == "kotlinx.coroutines.flow.Flow"
    }

    override fun <PRequest : Any> wrapResponse(
        returnTypeName: String,
        requestFunction: suspend () -> Pair<TypeInfo, HttpResponse>
    ): Any {
        return flow<ApiResponse<Any>> {
            try {
                val (info, response) = requestFunction()

                emit(ApiResponse.create(response.body(info.innerType()!!)))
            } catch (e: Throwable) {
                emit(ApiResponse.create(e))
            }
        }
    }
}
```

However I'd rather use suspend functions and not a Flow in the interface so please keep #23 open.

Hope I could help :)
