### ISSUE TITLE
`Field` in `FormUrlEncoded` encoded twice on Android + OkHttp

### ISSUE THREAD

**Issue by DanielNovak** [Foso/Ktorfit#21]
`Field` in `FormUrlEncoded` requests on Android with OkHttp gets encoded twice. For example `@` is encoded as `%2540` instead of `%40`. I suspect that OkHttp is doing encoding too. Tested on beta09.

**Comment by Foso** [comment]
Hi @DanielNovak , thank you for reporting this

**Comment by Foso** [comment]
Hi @DanielNovak , i just tried to reproduce the error with beta12, but everything worked fine. Please try if the error stills occurs for you

**Comment by Foso** [comment]
I'm closing this. If anyone can still reproduce this error, please reopen this ticket
