### ISSUE TITLE
PUT requires a url as parameter even though @Url is specified

### ISSUE THREAD

**Issue by DanielNovak** [Foso/Ktorfit#22]
The following code doesn't compile because `PUT` throws an error that `@Url` must be set in case no URL is forwarded into `PUT` directly - even though the `@Url` is specified:

```
    @PUT
    fun test(
        @Url url: String,
    ): Unit
```
It seems `@POST` has same problem.
`@GET` works correctly.

**Comment by Foso** [comment]
It should be fix now with v1.0.0-beta10
