### ISSUE TITLE
ResponseConverter ignored for suspend functions

### ISSUE THREAD

**Issue by DanielNovak** [Foso/Ktorfit#23]
The suspend API functions ignore any defined `ResponseConverters` - is that by design? A look into the source code confirms this, only the non-suspend code in KtorfitClient.request uses `getResponseConverters()`.

_*(I created a similar GH issue before and I closed it because it contained a lot of other noise)_

**Comment by DATL4G** [comment]
I would like to use my ResponseConverter for suspend functions as well.

An exmaple interface looks something like this:
```kotlin
interface Example {
    @GET("test")
    suspend fun getTest(): ApiResponse<String>
}
```

And my "possible" suspend ResponseConverter like this:

```kotlin
class ApiResponseConverter : ResponseConverter {
    override fun supportedType(returnTypeName: String): Boolean {
        return returnTypeName == "com.example.ApiResponse"
    }

    override suspend fun <PRequest : Any> wrapResponse(
        returnTypeName: String,
        requestFunction: suspend () -> Pair<TypeInfo, HttpResponse>
    ): Any {
        val (info, response)
        return ApiResponse.create(response)
    }
}
```

The ```wrapResponse``` should be a suspend function as well then, so the best thing would be separate class like ```SuspendResponseConverters``` I think.

Or the ```wrapResponse``` is always a suspend function, not sure if this is possible.

**Comment by Foso** [comment]
@DanielNovak  with beta11 it should work now with **SuspendResponseConverter**

**Comment by Foso** [comment]
I close this issue, if it's still relevant, fell free to reopen it
