### ISSUE TITLE
Document how to use custom Ktor client

### ISSUE THREAD

**Issue by mattrob33** [Foso/Ktorfit#3]
The [docs](https://foso.github.io/Ktorfit/#json) mention

> Ktorfit doesn’t parse JSON. You have to install the Json Feature to the Ktor Client that you add to Ktorfit

but never explain how to use your own Ktor client.

**Comment by Foso** [comment]
Sorry, for the very late reaction. I finally added it to the documentation https://foso.github.io/Ktorfit/configuration/#add-your-own-ktor-client
