### ISSUE TITLE
Add macosArm64 target in runtime library

### ISSUE THREAD

**Issue by hodgdon** [Foso/Ktorfit#315]
The runtime library is compiled for [macosX64](https://github.com/Foso/Ktorfit/blob/master/ktorfit-lib-common/build.gradle.kts#L69) but not macosArm64. It would be helpful for developing Mac apps to have both architectures.

**Comment by Foso** [comment]
Hi @hodgdon , thank you for pointing that out. The targets will be added

**Comment by Foso** [comment]
The targets are added with v1.4.0
