### ISSUE TITLE
need safe response converter

### ISSUE THREAD

**Issue by yang961226** [Foso/Ktorfit#389]
Retrofit's Response Converter supports converting the abnormal result into a successful result when an exception occurs during the network request process, but Ktorfit currently can only convert the case where no exception occurs, which makes me have to use try-catch to wrap For the request method, can I add a Converter so that I can continue to convert the result when the request reports an error instead of directly causing the framework to throw an exception

**Comment by Foso** [comment]
Hi, are you looking from something like de.jensklingenberg.ktorfit.Response ? 

```
interface ExampleApi{
  suspend fun getUser(): Response<User>
}

val userResponse = userKtorfit.create<ExampleApi>().getUser()
    
if(userResponse.isSuccessful){
  userResponse.body()
}else{
  userResponse.errorBody()
}
```

**Comment by Ric-AB** [comment]
In addition, when using response converter, I currently can't see any way to handle non-http exceptions from the docs. For example if there's no connectivity, UnresolvedHostException is thrown there's no way to handle such exceptions using response converters.

**Comment by yang961226** [comment]
What @Ric-AB said exactly what I wanted to say, UnresolvedHostException unable to handle non-Http exceptions,it just throw the exception and no way to handle it.

**Comment by Foso** [comment]
Hi, i understand the need for that feature and will make it work to handle these exception from inside a converter
