### ISSUE TITLE
Form fields: Unnecessary safe call on a non-null receiver of type String

### ISSUE THREAD

**Issue by Philio** [Foso/Ktorfit#449]
### Ktorfit version

1.7.0

### What happened and how can we reproduce this issue?

Code generated for form fields what are non-null have null safe access resulting in these warnings in build logs.
Granted they are harmless, it just creates a lot of noise in build outputs and in both Android Studio and Xcode.

### What did you expect to happen?

Access non null variables without null safe calls so the warnings disappear.

**Comment by Foso** [comment]
Hi, with Ktorfit 1.9.1 the warnings are suppressed. It's still planned to optimize the code, but that will come later.

**Comment by Philio** [comment]
Thanks very much @Foso, can confirm no warnings on 1.9.1 😄
