### ISSUE TITLE
linuxArm64 target support

### ISSUE THREAD

**Issue by sgpublic** [Foso/Ktorfit#475]
**Is your feature request related to a problem? Please describe.**
Thank you for the great work on ktorfit! As mentioned in the title, currently ktorfit does not have linuxArm64 support. Is there any plan to add linuxArm64 support? Or is there anything currently blocking this?

**Additional context**
I cloned the project, added the linuxArm64 target, and tried publishing the component locally, and it seemed like there would be no problem compiling.

**Comment by Foso** [comment]
Hi, i didn't know there is a linuxArm64 version of Ktor client. Cool to hear that is was compiling without problems. So the next Ktorfit version will have a linuxArm64 target

**Comment by sgpublic** [comment]
Thank you for your reply. I'm looking forward to the next release.

**Comment by Foso** [comment]
1.10.0 should work on linuxArm64
