### ISSUE TITLE
Using Subclass as return type generates uncompiled code due to missing import

### ISSUE THREAD

**Issue by DatL4g** [Foso/Ktorfit#486]
### Ktorfit version

1.10.1

### What happened and how can we reproduce this issue?

Having something like this does not compile correctly:

```kotlin
@Serializable
data class Query(
	@SerialName("working") val working: Working
) {
	@Serializable
	data class Working(
		@SerialName("data") val data: String	
	)

	@Serializable
	data class NotWorking(
		@SerialName("response") val reponse: String
	)
}


interface API {
	@Headers(
		"Content-Type: application/json",
		"Accept: application/json"
	)
	@POST("example/request")
	suspend fun query(@Body query: Query): List<Query.NotWorking> // not sure if non-list works, haven't tested
}
```

### What did you expect to happen?

The generated code has `List<NotWorking>` as return type and does not import it.

Either set `List<Query.NotWorking>` as return type or leave `List<NotWorking>` and add the import.

**Comment by Foso** [comment]
Hi @DatL4g  thank you for your bug report. I can reproduce that error and i'm working on a fix

**Comment by Foso** [comment]
With 1.10.2 it should work again
