### ISSUE TITLE
Wrong type conversion when using @Query 

### ISSUE THREAD

**Issue by hadiyarajesh** [Foso/Ktorfit#50]
**Describe the bug**
I'm using following function to make network request
```kotlin
@GET("v2/list")
suspend fun getAllImages(
    @Query("page") page: Int,
    @Query("size") size: Int = 30
): ApiResponse<List<Image>>
```

However, when I try to run the app, it throws compilation error and display error that `Type mismatch: inferred type is Int but Boolean was expected`
Whatever data type i use for `@Query("page") page: Int or String`, `QueryData(false,"page",page,QueryType.QUERY)` always generate `boolean` value type.

Below is the Implementation class generated by Ktorfir
```kotlin
public class _ImageApiImpl(
  private val client: KtorfitClient,
) : ImageApi {
  public override suspend fun getAllImages(page: Int, size: Int): ApiResponse<List<Image>> {
    val requestData = RequestData(method="GET",
        relativeUrl="v2/list",
        queries = listOf(QueryData(false,"page",page,QueryType.QUERY),  //This is error
            QueryData(false,"size",size,QueryType.QUERY)), //This is error
        qualifiedRawTypeName="com.hadiyarajesh.flower_core.ApiResponse") 

    return client.suspendRequest<ApiResponse<List<Image>>, List<Image>>(requestData)
  }
}
```
**To Reproduce**
Just use the same code I've mentioned

**Expected behavior**
App should compile and run without any issue

**Screenshots**
NA

**Software used**
```
Android studio Chipmank
Windows 11
```

**Additional context**
NA

**Comment by Foso** [comment]
Hi, which Ktorfit Version are you using?

**Comment by hadiyarajesh** [comment]
I'm using `1.0.0-beta12`

**Comment by Foso** [comment]
Try to clean and rebuild your project. I changed the order of the parameters of QueryData. It looks like the lib is beta12, but KSP is using beta11

**Comment by hadiyarajesh** [comment]
Yep, sorry, `ksp` was using `beta-09`
Thanks.

**Comment by alekseyHunter** [comment]
Hello, I also have the same problem - ktorfit 1.9.1, ksp 1.9.20-1.0.13, kotlin - 1.9.20
