### ISSUE TITLE
I can't import FlowResponseConverter in the latest version

### ISSUE THREAD

**Issue by ahmadmssm** [Foso/Ktorfit#502]
### Ktorfit version

1.11.0

### What happened and how can we reproduce this issue?

After updating to 1.11.0, I can no longer import Any response converter.

### What did you expect to happen?

Import Flow response converter or any other converter.

**Comment by Foso** [comment]
Hi, i cant not reproduce that error. Does it work here? : https://github.com/Foso/Ktorfit/tree/master/example/MultiplatformExample

**Comment by ahmadmssm** [comment]
I just pulled the latest version and in the source code, I can only see three converters, all of them are internal.

**Comment by ahmadmssm** [comment]
1.9.1

**Comment by bidrohi** [comment]
For me, it was failing on import, but got fixed once I applied the `ktorfit` plugin. Tried on 1.11.1 and 1.12.0
