### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by RhSantos** [Foso/Ktorfit#504]
**Is your feature request related to a problem?**
I'm trying to make an application with KMP but when i try to build my gradle dependencies, they don't work and my app don't have all techs that i can use to build a really multiplatform application.

**Describe the solution you'd like**
I would like to have a WASM support like others dependencies like koltinx coroutines.

**Describe alternatives you've considered**
The only alternative that i have is to comment the wasmJs from build.gradle.kts to work my Ktorfit dependency.

**Comment by Foso** [comment]
Hi, is there wasm dependency for Ktor client?

**Comment by Foso** [comment]
You need to add the io.ktor:ktor-client-core to commonMain and specific clients e.g. ktor-client-jvm to the specific target. The current version of Ktorfit will not work because the Ktorfit-lib is not compiled to wasm. Now that wasm is supported by Ktor i will of course also add the wasm target

**Comment by RhSantos** [comment]
Thank you for help me!

**Comment by Shusshu** [comment]
@Foso do you already have a beta/alpha version ?

**Comment by nowiwr01w** [comment]
@Foso Hey, how is it going?
