### ISSUE TITLE
Service from base class

### ISSUE THREAD

**Issue by dshatz** [Foso/Ktorfit#548]
**Is your feature request related to a problem? Please describe.**
I am trying to make a Ktorit service that would extend a base service.
Example:
```kotlin
// common service for all build variants
interface BaseMessageService {
    @GET(...)
    suspend fun baseCall(): String
}

// extended implementation for e.g. a different client
interface CustomMessageService {
   @GET(...)
   suspend fun otherCall(): Double
}
```
The goal is to have a `CustomService` on which both `baseCall` and `otherCall` are available.
Ksp compiles but I am getting this runtime error when calling `CustomMessageService.baseCall()`:

```
kotlin.UninitializedPropertyAccessException: lateinit property _converter has not been initialized
at _BaseMessageServiceImpl.get_converter
at _BaseMessageServiceImpl.baseCall
at _CustomMessageServiceImpl.baseCall
```

Creating CustomMessageService as usual `ktorfit.create<CustomMessageService()`.

**Describe the solution you'd like**
The error makes sense - the generated `CustomMessageServiceImpl` extends `BaseMessageService by _BaseMessageServiceImpl()`. That new instance does not have the _converter because it is created by `create` which is not called here.
Not sure what the solution could be. I understand this usecase is not supported now? I may try to hack something.

**Describe alternatives you've considered**
 - Copy paste base service methods to all extending services.
 - Abandon the idea of extending and just have two separate services.

**Comment by Foso** [comment]
Hi, that was working once, but it looks like it got broken. I fixed it and it will work again with > 2.0.0-beta2

**Comment by sschuberth** [comment]
Release [2.0.0](https://github.com/Foso/Ktorfit/releases/tag/2.0.0) says this was fixes... so I guess the issue should be closed?

**Comment by Foso** [comment]
@sschuberth You are right, thanks

**Comment by dshatz** [comment]
Maybe a good idea to document that this is supported.

**Comment by dshatz** [comment]
@Foso Hi! 
Is there a possibility to backport this to a pre-2.0.0 version?
I can't proceed with 2.0.0 because of #594
