### ISSUE TITLE
java.lang.IllegalStateException: _nullImpl() not found, did you apply the Ksp Ktorfit plugin?

### ISSUE THREAD

**Issue by sureshmaidaragi1919** [Foso/Ktorfit#557]
### Ktorfit version

2.0.0-rc01

### What happened and how can we reproduce this issue?

I have updated the kotlin v2.0.0 and Ktorfit version 2.0.0-rc01, on android build works fine, but on iOS I am getting build time error
![Screenshot 2024-05-24 at 1 10 51 PM](https://github.com/Foso/Ktorfit/assets/28126457/2f30a062-2c99-45fe-814f-dd9dae0ff4c0)

### What did you expect to happen?

Should rung on iOS app as well

**Comment by sureshmaidaragi1919** [comment]
Post updating to the latest version`ktorfitVersion = "2.0.0-rc01"`, started seeing the below issue of not found `Response`



![Screenshot 2024-05-24 at 1 30 09 PM](https://github.com/Foso/Ktorfit/assets/28126457/b06458ff-6b04-4363-b4c0-4bb67df85e9b)
![Screenshot 2024-05-24 at 1 30 06 PM](https://github.com/Foso/Ktorfit/assets/28126457/9639598a-ee73-481f-b667-84b16e0ffa10)

**Comment by Foso** [comment]
Hi, please do this: https://foso.github.io/Ktorfit/migration/#from-2-to-200

**Comment by Foso** [comment]
Is the issue still there?
