### ISSUE TITLE
WasmJs Support

### ISSUE THREAD

**Issue by eygraber** [Foso/Ktorfit#588]
### Is your feature request related to a problem? Please describe.

It would be nice to have wasmJs support in Ktorfit 

### Describe the solution you'd like

It looks like ktor will support wasmJs starting from 3.0.0-beta2.

**Comment by Foso** [comment]
Hi @eygraber , wasmJs support is planned, the problem is that i want to ship the library with latest stable of Ktor. And i can only add the wasmjs target when it would use 3.0.0-beta2.

**Comment by eygraber** [comment]
Have you considered making beta releases of Ktorfit? It would also probably make it easier to update to Ktor 3.0.0 once it is stable.

**Comment by Foso** [comment]
yes, i think i will do it that way

**Comment by eygraber** [comment]
Any update on this? Ktor 3.0.0-beta2 has been released.

**Comment by Foso** [comment]
Yes, with Ktorfit 2.0.1 you can use these dependencies for Ktor 3 https://github.com/Foso/Ktorfit?tab=readme-ov-file#ktorfit-ktor-3-packages

**Comment by eygraber** [comment]
Doesn't ktorfit itself have to add the `wasmJs` target?

**Comment by Foso** [comment]
It has, but only when it's published from the "ktor3" branch

**Comment by eygraber** [comment]
Oh I'm sorry, I read your previous message incorrectly. Thanks!
