### ISSUE TITLE
Ktorfit plugin doesn't include correct generate source if build directory changes

### ISSUE THREAD

**Issue by bidrohi** [Foso/Ktorfit#591]
### Ktorfit version

2.0.0

### What happened and how can we reproduce this issue?

If we change the build location, the Ktorfit plugin fails to include the generated source set for `commonMain`. 

In my project for example, I use the follow to move all the build directory in one location:

```
allprojects {
    layout.buildDirectory = File("${rootDir}/build/${projectDir.relativeTo(rootDir)}")
}
```

But doing so means when the Ktorfit plugin includes the generated location to the source set, being added by the following is incorrect:

```
kotlinExtension.sourceSets.named("commonMain").configure {
    kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin")
}
```

I believe, it should change to so that we don't hardcode `build` location

```
kotlinExtension.sourceSets.named("commonMain").configure {
    kotlin.srcDir("${layout.buildDirectory.get()}/generated/ksp/metadata/commonMain/kotlin")
}
```

### What did you expect to happen?

The change of `build` location has no impact

**Comment by Foso** [comment]
Hi @bidrohi thank you for your report. I hadn't thought about that case. Your idea sounds good!
