### ISSUE TITLE
Task with path 'kspCommonMainKotlinMetadata' not found in project

### ISSUE THREAD

**Issue by lepicekmichal** [Foso/Ktorfit#593]
### Ktorfit version

2.0.0

### What happened and how can we reproduce this issue?

Project doesn't compile when you have only one target in multiplatform project.
With error `Task with path 'kspCommonMainKotlinMetadata' not found in project`

Yes, it seems counterintuitive but there are scencarios when it makes sense, eg:

1. Just converting project from android only to multiplatform and can't do all of it at once
2. we do only android and ios, but most work is done on windows/linux, meaning ios sourceset is turned off for everyone but those who work on ios part with their mac os machines

### What did you expect to happen?

can compile

**Comment by Foso** [comment]
Thank you for the bug report!

**Comment by ArjenKellerICS** [comment]
is there progress on this?

**Comment by Foso** [comment]
I tried to find the workaround but i couldn't find a reliable one. The Kotlin team decided to handle single target compilation different to multiple targets, i don't know why

**Comment by Foso** [comment]
I found a workaround for that issue with Ktorfit 2.1.0
