### ISSUE TITLE
Endpoint with types from other module

### ISSUE THREAD

**Issue by dshatz** [Foso/Ktorfit#594]
### Ktorfit version

2.0.0

### What happened and how can we reproduce this issue?

 1. Kotlin 2.0.0, ksp 2.0.0-1.0.22 (ksp can be lower too), ktorfit 2.0.0
 2. `@GET` method in module 1 referencing a different module (included in classpath).
 3a. Return type is defined in a different module.
 3b. Annotation url parameter is a const from a different module.

Reproducible example: https://github.com/dshatz/ktorfit-demo

Error 3a.
```
java.lang.ClassCastException: class com.google.devtools.ksp.symbol.impl.kotlin.KSErrorType cannot be cast to class java.lang.String (com.google.devtools.ksp.symbol.impl.kotlin.KSErrorType is in unnamed module of loader java.net.URLClassLoader @6c159f80; java.lang.String is in module java.base of loader 'bootstrap')
```

Error 3b.
```
[ksp] java.lang.IllegalArgumentException: Error type '<ERROR TYPE: ExternalModel>' is not resolvable in the current round of processing.
```

### What did you expect to happen?

This has worked sometime ago with Kotlin 1.9.23

**Comment by dshatz** [comment]
I can see that you are using `getSymbolsWithAnnotation`.
According to this (https://github.com/google/ksp/issues/1075), this will not return declarations from the classpath.

**Comment by Foso** [comment]
Thank you for the report and example repo! I always used getSymbolsWithAnnotation so i'm suprised that it was working before 🤔

**Comment by dshatz** [comment]
Confirmed working on 1.3.1 (Kotlin 1.9.23)
https://github.com/dshatz/ktorfit-demo/commit/f3fcd2abb47032b428fd9fe8b0e58246c3ffb6f4

**Comment by Foso** [comment]
I tried it with getDeclarationsFromPackage but that also can't resolve the ExternalModel class

**Comment by Foso** [comment]
Hi, with 2.0.1 this should be fixed
