### ISSUE TITLE
Could not find de.jensklingenberg.ktorfit:ktorfit-ksp:2.0.0-1.0.24 after updating ksp to 2.0.0-1.0.24

### ISSUE THREAD

**Issue by dawidhyzy** [Foso/Ktorfit#622]
### Ktorfit version

2.0.0

### What happened and how can we reproduce this issue?

> Could not resolve all files for configuration ':network:common:_agp_internal_javaPreCompileDebug_kspClasspath'.
   > Could not find de.jensklingenberg.ktorfit:ktorfit-ksp:2.0.0-1.0.24.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/de/jensklingenberg/ktorfit/ktorfit-ksp/2.0.0-1.0.24/ktorfit-ksp-2.0.0-1.0.24.pom
       - https://repo.maven.apache.org/maven2/de/jensklingenberg/ktorfit/ktorfit-ksp/2.0.0-1.0.24/ktorfit-ksp-2.0.0-1.0.24.pom
       - https://artifact.plugin.npaw.com/artifactory/plugins/android/de/jensklingenberg/ktorfit/ktorfit-ksp/2.0.0-1.0.24/ktorfit-ksp-2.0.0-1.0.24.pom
     Required by:
         project :network:common

### What did you expect to happen?

Project to compile

**Comment by frist008** [comment]
same

**Comment by Foso** [comment]
It's now available
