### ISSUE TITLE
Kotlin 2.0.10 Support

### ISSUE THREAD

**Issue by Ph1ll1pp** [Foso/Ktorfit#626]

**Comment by dawidhyzy** [comment]
It blocks Kotlin update for me:
```
> Could not find de.jensklingenberg.ktorfit:compiler-plugin:2.0.1-2.0.10.
--
4968 | Searched in the following locations:
4969 | - https://dl.google.com/dl/android/maven2/de/jensklingenberg/ktorfit/compiler-plugin/2.0.1-2.0.10/compiler-plugin-2.0.1-2.0.10.pom
4970 | - https://repo.maven.apache.org/maven2/de/jensklingenberg/ktorfit/compiler-plugin/2.0.1-2.0.10/compiler-plugin-2.0.1-2.0.10.pom
4971 | - https://artifact.plugin.npaw.com/artifactory/plugins/android/de/jensklingenberg/ktorfit/compiler-plugin/2.0.1-2.0.10/compiler-plugin-2.0.1-2.0.10.pom
```
@Foso as I raised a similar issue before https://github.com/Foso/Ktorfit/issues/622 I wondered if there is a way to automate this.

**Comment by Foso** [comment]
It's now avaible. 

I think there is a way to automate it. The challenge is that the Kotlin Compiler Api and Ksp Api is still not stable, so if there is a breaking change i still need to manually release compatible version for every new Kotlin / KSP version
