### ISSUE TITLE
[Bug]: Android overload resolution ambiguity

### ISSUE THREAD

**Issue by 89jd** [Foso/Ktorfit#64]
### Ktorfit version

1.0.0-beta13

### What happened and how can we reproduce this issue?

```
Overload resolution ambiguity: 
public inline fun <reified T> Ktorfit.create(): TypeVariable(T) defined in de.jensklingenberg.ktorfit
public inline fun <reified T> Ktorfit.create(): TypeVariable(T) defined in de.jensklingenberg.ktorfit
```

Makes sense that this is happening, as the generated package is the same as the original definition. Should the created file be in the same package as the class that uses it so then we don't need to import anything?

### What did you expect to happen?

Pick up the correct create method

**Comment by DATL4G** [comment]
Just experienced the same issue on a multiplatform project.

As a workaround you can create you interface like this:

```kotlin
package your.package.network // !!! REMEMBER THIS !!!

import de.jensklingenberg.ktorfit.http.GET
import io.ktor.client.statement.*

interface Example {
    @GET("test")
    suspend test(): HttpResponse
}
```

```kotlin

/**
  ADD YOUR PACKAGE NAME HERE

  The create method name is made of: "create" + interface name
*/
import your.package.network.createExample

val ktorfit = ktorfit {
    baseUrl("https://example.com/")
}
val exampleInstance = ktorfit.createExample()
```

**IntelliJ or Android Studio may show an error on the import, you can ignore that as long as the build is successful.**

@Foso maybe count the creation of the create method or something like this to check if it's already present

**Comment by Foso** [comment]
HI, please try 1.0.0-beta17, the create method is not generated anymore, so this error should not occur anymore
