### ISSUE TITLE
Generated classes do not propagate opt-in ExperimentalUuidApi

### ISSUE THREAD

**Issue by markocic** [Foso/Ktorfit#666]
### Ktorfit version

2.1.0

### What happened and how can we reproduce this issue?

I am using new Uuid API that was shipped with kotlin 2.0.20 and have an interface defining Stores API implemented like this:
```kt
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

@OptIn(ExperimentalUuidApi::class)
interface StoresApi {

    @GET("v1/stores")
    suspend fun getStores(
        @Query("workspaceId") workspaceId: Uuid,
        @Query("after") after: Instant? = null,
    ): PagedDataResponse<StoreApiModel>

    @GET("v1/stores/{storeId}")
    suspend fun getStoreById(
        @Path("storeId") storeId: Uuid,
    ): ReceiptResponse

}
```

Interface written like this will fail at build time with a message:
> android/business/api/_StoresApiImpl.kt:35:47 This declaration needs opt-in. Its usage must be marked with `@kotlin.uuid.ExperimentalUuidApi` or `@OptIn(kotlin.uuid.ExperimentalUuidApi::class)`

### What did you expect to happen?

I expected build to be successful and for Ktorfit to propagate `@OptIn(ExperimentalUuidApi::class)` annotation to generated classes.

**Comment by Foso** [comment]
It's fixed with Ktorfit 2.2.0
