### ISSUE TITLE
Add nullable field parameters support

### ISSUE THREAD

**Issue by Syer10** [Foso/Ktorfit#67]
**Is your feature request related to a problem? Please describe.**
Similar to #10, but it may not be covered in a fix specifically made for #10.
I use an api that supports modifying an object using a form. The fields are nullable since they are not required and should only be added when you are modifying that field.

**Describe the solution you'd like**
Add support for something like `@Field("string") nullableString: String?`

**Describe alternatives you've considered**
Currently I have implemented it in my application using multiple functions, one for each field.

**Additional context**
Example of what I would like to be able to do
```kotlin
    @FormUrlEncoded
    @PATCH("/api/v1/manga/{mangaId}/chapter/{chapterIndex}")
    fun updateChapter(
        @Path("mangaId") mangaId: Long,
        @Path("chapterIndex") chapterIndex: Int,
        @Field("read") read: Boolean? = null,
        @Field("bookmarked") bookmarked: Boolean? = null,
        @Field("lastPageRead") lastPageRead: Int? = null,
        @Field("markPrevRead") markPreviousRead: Boolean? = null
    ): Flow<HttpResponse>
```

**Comment by Foso** [comment]
Hi @Syer10 , i will add this feature. I just added support for nullable query parameters and i think it can be implemented the same way for fields
