### ISSUE TITLE
Does it support wasm in web

### ISSUE THREAD

**Issue by nasamio** [Foso/Ktorfit#675]

**Comment by Foso** [comment]
Yes, https://github.com/Foso/Ktorfit/tree/master?tab=readme-ov-file#ktorfit-ktor-3-packages

**Comment by nasamio** [comment]
> Yes, https://github.com/Foso/Ktorfit/tree/master?tab=readme-ov-file#ktorfit-ktor-3-packages

thanks,i'll try it later.
