### ISSUE TITLE
Ktor 3 support

### ISSUE THREAD

**Issue by smelfungus** [Foso/Ktorfit#681]
### Is your feature request related to a problem? Please describe.

Hi! Thank you for the fantastic library. I noticed that Ktor 3.0 has been released, and it might be a good time to consider upgrading Ktorfit to be compatible with the latest version.

Thanks again for your hard work!

**Comment by Foso** [comment]
Dependencies for Ktor3 are online: https://github.com/Foso/Ktorfit?tab=readme-ov-file#ktorfit-ktor-3-packages
