### ISSUE TITLE
How to generate the `_FooApiImpl.kt` in `commonMain` instead of `jvmMain`?

### ISSUE THREAD

**Issue by opatry** [Foso/Ktorfit#705]
Not sure it's an issue or something I missed, but I noticed that I wasn't able to reach the `Ktorfit.createFooApi()` extension in my setup, only the deprecated `Ktorfit.create<FooApi>()` was available.

I have the following project structure:

- `:lib1`
  - which contains the `FooApi` interface
  - and is a KMP module with all source code in `commonMain`
- `:logic-core`
  - consuming/depending on `:lib1`
  - not needing the Ktorfit factory, just consuming the `FooApi` interface. All source code in `commonMain`
- `:shared`
  - which is a KMP module consuming `:logic-core`
  - 99% of the code being in `commonMain`, only few things in `jvmMain` (desktop) or `androidMain` (android)
  - This is the module defining the `FooApi` impl factory using `Ktorfit.create*()`, in code defined in `commonMain`.
- `:desktop-app`
  - instantiate the DI graph for desktop
- `:android-app`
  - instantiate the DI graph for desktop

The `_FooApiImpl.kt` class is generated in `lib1/build/generated/ksp/jvm/jvmMain/kotlin`, it appears that because of this, I can't reach the class from `:shared/src/commonMain/kotlin`.

Is there a way to tweak where the code is generated, or alternatively, generate it in `commonMain`?

**Comment by Foso** [comment]
Hi, the code is not generated to commonMain, because your :lib1 is only having a single compile target https://foso.github.io/Ktorfit/knownissues/#kmp-project-with-single-target

**Comment by opatry** [comment]
Oh, I missed that section in the doc, it explains the issue indeed.
Thanks.
