### ISSUE TITLE
Ktorfit Avoids Dependency Injection with Koin for iOS

### ISSUE THREAD

**Issue by brsuslcn** [Foso/Ktorfit#717]
### Ktorfit version

2.1.0

### What happened and how can we reproduce this issue?

I have correctly implemented dependency injection, and everything functions well on Android without issues. However, I am experiencing problems on iOS. I initialize Koin separately for both Android and iOS. When I remove Ktorfit from the modules, the application works fine, but it does not function correctly when Ktorfit is included.

SplashViewModel contains repository which are from ktorfit.

![ss2](https://github.com/user-attachments/assets/6e3b7da4-44c0-48c4-87ba-72ac834aa48d)

### What did you expect to happen?

It shouldn't make problems for injection.

### Is there anything else we need to know about?

`val apiModule = module {

    single<AuthTokenProvider> { AuthTokenProvider(get()) }

    single {
        Ktorfit.Builder()
            .httpClient {
                install(ContentNegotiation) {
                    json(Json { isLenient = true; ignoreUnknownKeys = true })
                }
                install(DefaultRequest) {
                    header(HttpHeaders.ContentType, ContentType.Application.Json)
                }

                install("AuthPlugin") {
                    val tokenProvider: AuthTokenProvider = get()
                    requestPipeline.intercept(HttpRequestPipeline.State) {
                        val token = tokenProvider.getToken()
                        if (token != null) {
                            context.headers.append(HttpHeaders.Authorization, "Bearer $token")
                        }
                    }
                }
            }
            .baseUrl(BASE_URL)
            .build()
    }

    single<AuthService> { get<Ktorfit>().createAuthService() }
    single<ComplaintService> { get<Ktorfit>().createComplaintService() }
    single<AnnouncementService> { get<Ktorfit>().createAnnouncementService() }
}

fun initializeKoin(
    androidViewModelModule: Module? = null
) {
    startKoin {
        modules(getAppModules(androidViewModelModule))
    }
}

private fun getAppModules(androidViewModelModule: Module?): List<Module> {
    val commonModules = listOf(repositoryModule, apiModule, viewModelModule)
    return if (androidViewModelModule != null) {
        commonModules + androidViewModelModule
    } else {
        commonModules
    }
}`

**Comment by geworfener** [comment]
Might be related to #720, please check the root cause.

**Comment by brsuslcn** [comment]
i implemented io.ktor:ktor-client-ios, and it solved. Thanks!
