### ISSUE TITLE
Ksp 1.0.26

### ISSUE THREAD

**Issue by Foso** [Foso/Ktorfit#718]
I looked into it, it is raising the JVM target from 8 to 11 by mistake. It is already reverted https://github.com/google/ksp/commit/579c9daf5227d736520b9bbd07dd5de962e9f138 I will wait a few days if there will be a Ksp Hotfix release. I don't want to raise the JVM target and then lower it again

**Comment by Foso** [comment]
The plugin is now online

**Comment by fayzfi** [comment]
@Foso [1.0.27](https://github.com/google/ksp/releases/tag/2.0.21-1.0.27) and kotlin [2.1.0-RC](https://github.com/google/ksp/releases/tag/2.1.0-RC-1.0.27) is live now :)
