### ISSUE TITLE
Allow using Body in Non-Body methods

### ISSUE THREAD

**Issue by Tommyten** [Foso/Ktorfit#77]
**Is your feature request related to a problem? Please describe.**
Currently when trying to call a non-body method like `DELETE` ktorfit throws an error.

**Describe the solution you'd like**
Make it possible either to call non-body methods with a body.
Either make the error be a warning or allow turning the error off with some kind of flag.

**Additional context**
While I support the decision to discourage non-standard use of HTTP, it (unfortunately) is a reality that we don't always have control over the APIs we use. In such cases using ktorfit is out of question as it does not support these unconventional usecases.

**Comment by Foso** [comment]
Hi, i understand the need for that feature. I want to keep the error checking by default, but i like the idea of adding a flag to disable it/turn it into warnings.
