### ISSUE TITLE
Problematic ksp version update

### ISSUE THREAD

**Issue by EvgenyPlaksin** [Foso/Ktorfit#9]
I use ktorfit in my app. I tried to update the version of the ksp plugin to the latest one, different from the one in the example. After the update, the generated class _ApiServiceImpl began to inherit from some _AnyImpl. Because of this, I got this error:
`Only interfaces can by delegated to`
and also 
`Unresolved reference: _AnyImpl`
 When downgrading, everything becomes fine, but I would like to use a newer version of Kotlin in my project, which the old version of the ksp plugin does not allow. 

More specifically about versions:
Old version of ksp:
`1.6.10-1.0.4`
New version of ksp:
`1.6.21-1.0.5`
Old kotlin version:
`1.5.31`
New kotlin version:
`1.6.20`

Class code with an error:
`class _ApiServiceImpl(val client : KtorfitClient)  : ApiService , kotlin.Any by kotlin._AnyImpl(client){
// Other maybe normal code
}`

can you suggest me how to solve this problem? Maybe I missed something, or is it a problem of the library itself?

**Comment by Foso** [comment]
Hi @EvgenyPlaksin is the problem solved with 1.0.0-beta06?

**Comment by EvgenyPlaksin** [comment]
Yes, thank you. The problem was solved

**Comment by EvgenyPlaksin** [comment]
I apologize for not answering for so long, there was no time to test the new version.
