### ISSUE TITLE
[Bug]: Form data is double encoded

### ISSUE THREAD

**Issue by Philio** [Foso/Ktorfit#95]
### Ktorfit version

1.0.0-beta16

### What happened and how can we reproduce this issue?

Sending a request using `@FormUrlEncoded` results in data being encoded twice if string contains special characters.

### What did you expect to happen?

Special characters should be encoded once.

### Is there anything else we need to know about?

As a work around I am using `@Field("whatever", true)` and using unencoded strings. Data is still encoded, but only once. I assume that Ktor is also encoding form data so Ktorfit probably doesn't need to. But that's just a guess.

**Comment by Foso** [comment]
Hi @Philio , thank you for reporting. I fixed this issue with [v1.0.0-beta17](https://github.com/Foso/Ktorfit/releases/tag/v1.0.0-beta17)
