### ISSUE TITLE
Add ability to specify default coroutines dispatcher

### ISSUE THREAD

**Issue by geworfener** [Foso/Ktorfit#97]
Does it make sense to add the ability to specify a default coroutines dispatcher for all calls? Retrofit defaults to Dispatchers.IO, but that's currently only available on JVM targets (see https://github.com/Kotlin/kotlinx.coroutines/issues/3205).

**Comment by Foso** [comment]
Hi, thank you for the idea. But i think this should be handled outside of Ktorfit
